version: "3"

services:
    qdrant:
        image: qdrant/qdrant
        container_name: vector_db
        restart: always
        ports:
            - "6335:6333"
        volumes:
            - qdrant-data:/qdrant/data

    redis:
        image: redis
        container_name: chat_history_db
        restart: always
        ports:
            - "127.0.0.1:6369:6379"
        environment:
            REDIS_PASSWORD: redis_password
            REDIS_USERNAME: redis_username
        command:
            - /bin/sh
            - -c
            - redis-server --protected-mode no --requirepass $${REDIS_PASSWORD}

volumes:
    qdrant-data:
